version: '2'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    environment:
      DEFAULT_HOST: my.domain.com
    restart: on-failure:10
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - sails
    networks:
      - front-tier

  sails:
    build: ..
    environment:
      DB_HOST: postgres
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: dbname
      SESSION_SECRET: my_session_secret
      PORT: 1337
      VIRTUAL_HOST: my.domain.com
      NODE_ENV: development
    restart: on-failure:10
    tty: true
    user: root
    networks:
      - front-tier
      - back-tier
    volumes:
      - ..:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:9
    container_name: postgres
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    restart: on-failure:10
    volumes:
      - datapersistance:/var/lib/postgresql/data
    networks:
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  datapersistance:
    driver: local
  node_modules:
    driver: local
